enum {
	ERROR_NONE,
	ERROR_MEMORY_FAILURE,
	ERROR_UNKNOWN_PROTOCOL,
	ERROR_INVALID_DATA,
	ERROR_INVALID_COMMAND_NAME,
	ERROR_TERMBOX_FAILURE,
	ERROR_NULL_ARGUMENT,
	ERROR_INVALID_URL,
	ERROR_INVALID_PORT,
	ERROR_GETADDRINFO, /* gai_strerror */
	ERROR_INVALID_ADDRESS,
	ERROR_BUFFER_OVERFLOW,
	ERROR_SOCKET_CREATION,
	ERROR_SOCKET_CONNECTION,
	ERROR_TOO_MANY_REDIRECT,
	ERROR_TLS_FAILURE,
	ERROR_INVALID_STATUS,
	ERROR_INVALID_METADATA,
	ERROR_NO_CRLN
};

int error_string(int error, char *out, size_t len);
